version: '3.7'

services:
  # MySQL 8 service
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container      
    volumes:
      - data:/var/lib/mysql 
    restart: always # Volume para persistir os dados do MySQL
  
  # Redis service
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" # Mapeamento da porta do host para a porta do contêiner
  
  rabbitmq:
    image: rabbitmq:3.12-management #escolhar versao com  - management para poder abrir ele na url com interface gráfica para administrar e gerenciar as filas
    ports:
      - 15672:15672 # use http://localhost:15672/ e vai entrar na interface gráfica para administrar e gerenciar as filas
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  # NestJS service
  nestjs:
    build: 
      context: .
      dockerfile: Dockerfile # Caminho para o Dockerfile do NestJS
    restart: always
    ports:
      - "3000:3000" # Mapeamento da porta do host para a porta do contêiner
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env

volumes:
  data: